### PR TITLE
add async support

### PR DESCRIPTION
**Pull request by andresv**
This PR adds `embedded-hal-async` support if `async` feature flag is enabled.

### CODE REVIEW

**Review by teamplayer3 — COMMENTED** [review]
First of all thanks for adding async support. I'm a fan of putting the docstring before the 'cfg' attributes. Could you change the ordering or whats your opinion on that.

**Comment by andresv** [comment]
Changed the order and removed duplicated doc comments.

**Review by teamplayer3 — COMMENTED** [review]
I think we should leave the comments for the async functions to have them visible if the async feature ist enabled.

**Comment by andresv** [comment]
Indeed such cfg trick did not work and I added duplicated docs back for async.

**Pull request merged**
